#app.yaml
runtime: python27
api_version: 1 #Only one version of app engine runtime
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
